### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by dsivasuthan** [shmink/pop-launcher-dictionary#1]
I assuming there is an issue with the path in the script. I ran into the following error.

```
cp: cannot stat 'launcher-plugin-define/': No such file or directory
chmod: cannot access '/home/_/.local/share/pop-launcher/plugins/define/define': No such file or directory
```

**Comment by shmink** [comment]
Thank you for the feedback :)

**Comment by dsivasuthan** [comment]
Hey, thanks for fixing that. This time the script finished running without issue but it doesn't work. When I hit Super key, and type out "define book", the following comes up.

![image](https://user-images.githubusercontent.com/1507367/178599918-fc3b642a-5eb4-4f0b-a1f6-48babe6c0895.png)

And when I hit Enter, nothing happens. What kind of info do you need to troubleshoot this? Maybe you can delete the plugin on your machine and install using the script?
